# Generated by Django 4.0.3 on 2022-08-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_singleimage_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleimage',
            name='userId',
        ),
    ]
