# Generated by Django 4.0.3 on 2022-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_singleimage_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='myImg',
            field=models.ImageField(upload_to=''),
        ),
    ]
