# Generated by Django 4.0.3 on 2022-08-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_singleimage_myimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setfile',
            name='userId',
        ),
    ]
