# Generated by Django 4.0.3 on 2022-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_setfile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setfield',
            name='userId',
        ),
    ]
