# Generated by Django 4.0.3 on 2022-09-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_setfield_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='userRoll',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
